name: deutsches_worterbuch
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1
  provider: ^6.1.1
  # Responsividade
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

flutter:
  uses-material-design: true